version: '2'
services:
    jhipsteredocapplication-app:
        image: jhipsteredocapplication
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://jhipsteredocapplication-postgresql:5432/jhipsterEdocApplication
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipsteredocapplication-postgresql:
        extends:
            file: postgresql.yml
            service: jhipsteredocapplication-postgresql
