version: '2'
services:
    jhipsteredocapplication-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/jhipsterEdocApplication/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=jhipsterEdocApplication
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
